# Generated by Django 3.2 on 2022-02-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('DesignerID', models.AutoField(primary_key=True, serialize=False)),
                ('DesignerFName', models.CharField(max_length=50)),
                ('DesignerLName', models.CharField(max_length=50)),
                ('DesignerEmail', models.EmailField(max_length=150)),
                ('DesignerNumber', models.IntegerField()),
                ('DesignerJob', models.CharField(max_length=150)),
                ('DesignerPass', models.CharField(max_length=25)),
                ('UDesignerPhoto', models.ImageField(upload_to='')),
                ('JoinedAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('OID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('OType', models.CharField(max_length=15)),
                ('OImage', models.ImageField(upload_to='')),
                ('AddedAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=200)),
                ('JoinedAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserFName', models.CharField(max_length=50)),
                ('UserLName', models.CharField(max_length=50)),
                ('UserEmail', models.EmailField(max_length=150)),
                ('UserNumber', models.IntegerField()),
                ('UserJob', models.CharField(max_length=150)),
                ('UserPass', models.CharField(max_length=25)),
                ('UserPhoto', models.ImageField(upload_to='')),
                ('JoinedAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('TempID', models.AutoField(primary_key=True, serialize=False)),
                ('TempName', models.CharField(max_length=70)),
                ('TempDesc', models.CharField(max_length=500)),
                ('Tempfile', models.FileField(upload_to='')),
                ('TempImg', models.ImageField(upload_to='')),
                ('AddedAt', models.DateField(auto_now_add=True)),
                ('tempAthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot.suscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('MailID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=70)),
                ('Message', models.CharField(max_length=2000)),
                ('SentAt', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot.suscriber')),
            ],
        ),
    ]
