# Generated by Django 3.2 on 2022-02-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='UDesignerPhoto',
        ),
        migrations.AddField(
            model_name='designer',
            name='DesignerPhoto',
            field=models.ImageField(default='static/assets/img/py.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='template',
            name='TempPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
