# Generated by Django 4.0.1 on 2022-02-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0002_auto_20220203_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='DesignerPhoto',
            field=models.ImageField(default='py.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='tempAthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot.designer'),
        ),
    ]
