# Generated by Django 4.0.1 on 2022-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0003_alter_designer_designerphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='TempType',
            field=models.CharField(default='Kivymd', max_length=20),
        ),
    ]
